apiVersion: v1
kind: Service
metadata:
  name: backend-feed
  labels:
    service: backend-feed
spec:
  ports:
  - port: 8080
    name: "8080"
    targetPort: 8080
  selector:
    service: backend-feed