apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: captchacoder/udagram-api-feed:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: 200m
          limits:
            memory: "1024Mi"
            cpu: 500m
        envFrom:
          - configMapRef:
              name: env-config
          - secretRef:
             name: env-secret
